# Generated by Django 4.0.5 on 2022-06-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0002_pet_historia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="historia",
            field=models.TextField(),
        ),
    ]
